-- MySQL Script generated by MySQL Workbench
-- do 28 mei 2015 11:26:26 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CMS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CMS` ;

-- -----------------------------------------------------
-- Schema CMS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CMS` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `CMS` ;

-- -----------------------------------------------------
-- Table `CMS`.`Gebruikers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CMS`.`Gebruikers` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Naam` VARCHAR(255) NOT NULL,
  `Wachtwoord` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(80) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMS`.`Images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CMS`.`Images` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Path` VARCHAR(255) NOT NULL,
  `Locatie` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMS`.`Categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CMS`.`Categorie` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Naam` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMS`.`Content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CMS`.`Content` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Locatie` VARCHAR(255) NOT NULL,
  `Text` LONGTEXT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMS`.`Recenties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CMS`.`Recenties` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Naam` VARCHAR(45) NULL,
  `Recentie` LONGTEXT NULL,
  `Rating` VARCHAR(45) NULL,
  `Akkoord` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMS`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CMS`.`Menu` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Naam` VARCHAR(45) NULL,
  `Prijs` VARCHAR(45) NULL,
  `Beschrijving` VARCHAR(45) NULL,
  `Images_ID` INT NOT NULL,
  `Categorie_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Menu_Images_idx` (`Images_ID` ASC),
  INDEX `fk_Menu_Categorie1_idx` (`Categorie_ID` ASC),
  CONSTRAINT `fk_Menu_Images`
    FOREIGN KEY (`Images_ID`)
    REFERENCES `CMS`.`Images` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Menu_Categorie1`
    FOREIGN KEY (`Categorie_ID`)
    REFERENCES `CMS`.`Categorie` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMS`.`Reservering`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CMS`.`Reservering` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Voornaam` VARCHAR(45) NULL,
  `Achternaam` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Telefoonnummer` INT NOT NULL,
  `Aantal` INT NOT NULL,
  `Extra` LONGTEXT NULL,
  `Datum` DATE NULL,
  `Tijd` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMS`.`Artikelen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CMS`.`Artikelen` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Titel` VARCHAR(45) NULL,
  `Text` LONGTEXT NULL,
  `Images_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Artikelen_Images1_idx` (`Images_ID` ASC),
  CONSTRAINT `fk_Artikelen_Images1`
    FOREIGN KEY (`Images_ID`)
    REFERENCES `CMS`.`Images` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;